ecommerce:
  target: dev
  outputs:
    dev:
      type: redshift
      host: "{{ env_var('HOST') }}"
      user: "{{ env_var('USER') }}"
      password: "{{ env_var('PASSWORD') }}"
      port: 5439
      dbname: ecommerce
      schema: dev
      threads: 4